#configuration for ptp4l service
##########################################################


#specify the interfaces used for time synchronisation
#when multiple interfaces given, a clock transparent gptp bridge can be established 
PTP4L_INTERFACES=tsn4

#ptp4l configuration file name
PTP4L_CONFIG_FILE=/etc/ptp4l/ptp4l_slave.cfg
